spring.application.name=Product-Master

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/product_master
spring.datasource.username=postgres
spring.datasource.password=Yashodharjadav@1425

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080