spring:
  application:
    name: Product-Master

  datasource:
    url: jdbc:postgresql://localhost:5432/product_master
    username: postgres
    password: Yashodharjadav@1425

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080